% generated by viz_events.m

%load mat/tc_ons.mat;
load mat/tc4_ons.mat;

% ver 1: before refactor, full finalTimeStepList history
% ver 2: before refactor, reset finalTimeStepList for each play
% ver 3: refactor, reset finalTimeStepList for each play
% ver 4: refactor, reset finalTimeStepList for each block

% almost all the differences between refactored (3) and non-refactored (2) are explained by sprites, except for one in run 4

for r = 1:6
    r

    tc_d34 = tc_ons3{r}(find(~ismember(tc_ons3{r}, tc_ons4{r})));
    tc_d43 = tc_ons4{r}(find(~ismember(tc_ons4{r}, tc_ons3{r})));
    sc_d34 = sc_ons3{r}(find(~ismember(sc_ons3{r}, sc_ons4{r})));
    sc_d43 = sc_ons4{r}(find(~ismember(sc_ons4{r}, sc_ons3{r})));
    ic_d34 = ic_ons3{r}(find(~ismember(ic_ons3{r}, ic_ons4{r})));
    ic_d43 = ic_ons4{r}(find(~ismember(ic_ons4{r}, ic_ons3{r})));
    tec_d34 = tec_ons3{r}(find(~ismember(tec_ons3{r}, tec_ons4{r})));
    tec_d43 = tec_ons4{r}(find(~ismember(tec_ons4{r}, tec_ons3{r})));

    if length(tc_d34) > 0
        assert(all(ismember(tc_d34, sc_d34)));
    end
    if length(tc_d43) > 0
        assert(all(ismember(tc_d43, sc_d43)));
    end
end

% =>
%{
for r = 1:6
    r

    tc_d14 = tc_ons1{r}(find(~ismember(tc_ons1{r}, tc_ons4{r})));
    tc_d41 = tc_ons4{r}(find(~ismember(tc_ons4{r}, tc_ons1{r})));
    sc_d14 = sc_ons1{r}(find(~ismember(sc_ons1{r}, sc_ons4{r})));
    sc_d41 = sc_ons4{r}(find(~ismember(sc_ons4{r}, sc_ons1{r})));
    ic_d14 = ic_ons1{r}(find(~ismember(ic_ons1{r}, ic_ons4{r})));
    ic_d41 = ic_ons4{r}(find(~ismember(ic_ons4{r}, ic_ons1{r})));
    tec_d14 = tec_ons1{r}(find(~ismember(tec_ons1{r}, tec_ons4{r})));
    tec_d41 = tec_ons4{r}(find(~ismember(tec_ons4{r}, tec_ons1{r})));

    if length(tc_d14) > 0
        assert(all(ismember(tc_d14, sc_d14)));
    end
    if length(tc_d41) > 0
        assert(all(ismember(tc_d41, sc_d41)));
    end
end
%}

%{
for r = 1:6
    r

    tc_d23 = tc_ons2{r}(find(~ismember(tc_ons2{r}, tc_ons3{r})));
    tc_d32 = tc_ons3{r}(find(~ismember(tc_ons3{r}, tc_ons2{r})));
    sc_d23 = sc_ons2{r}(find(~ismember(sc_ons2{r}, sc_ons3{r})));
    sc_d32 = sc_ons3{r}(find(~ismember(sc_ons3{r}, sc_ons2{r})));
    ic_d23 = ic_ons2{r}(find(~ismember(ic_ons2{r}, ic_ons3{r})));
    ic_d32 = ic_ons3{r}(find(~ismember(ic_ons3{r}, ic_ons2{r})));
    tec_d23 = tec_ons2{r}(find(~ismember(tec_ons2{r}, tec_ons3{r})));
    tec_d32 = tec_ons3{r}(find(~ismember(tec_ons3{r}, tec_ons2{r})));

    % of the theory_change_flags that differ between 2 and 3, how many are from differences in the sprites?
    if length(tc_d23) > 0
        assert(all(ismember(tc_d23, sc_d23)));
    end
    if length(tc_d32) > 0
        assert(all(ismember(tc_d32, sc_d32)));
    end
end
%}
